-- create database itau;
-- use itau;
-- show tables

/* create table itau.clientes(
codigo_cliente integer not null,
nome_cliente varchar(50) not null,
idate_cliente integer(3) not null,
email_cliente varchar(80) not null,

primary key (codigo_cliente)
);
*/
/*
-- describe itau.clientes
insert into itau.clientes
(codigo_cliente,nome_cliente,idate_cliente,email_cliente)
values
(8, "zero oito", 17,"zerooito@um.com.br"),
(9, "zero nove", 22,"zeronove@dois.com.br"),
(10, "zero dez", 33,"zerodez@tres.com.br"),
(11, "zero onze", 37,"zeroonze@quatro.com.br"),
(12, "zero doze", 14,"zerodoze@cinco.com.br"),
(13, "zero treze", 18,"zehtreze@treze.com.br"),
(14, "cuatorze", 20,"cuatorze@sete.com.br")

*/

-- select * from itau.clientes order by nome_cliente
-- select nome_cliente,idate_cliente from itau.clientes order by nome_cliente
-- use itau
/*
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (15,"Ian Y. Morrison",47,"molestie@tellus.org"),(16,"Colorado K. Wallace",53,"non.justo@vitae.ca"),(17,"Rylee Anthony",25,"augue@etmagnis.co.uk"),(18,"Salvador T. Calhoun",62,"tellus.lorem.eu@quisdiam.ca"),(19,"Troy Mcdaniel",71,"interdum.feugiat.Sed@tristiquealiquetPhasellus.net"),(20,"Drew O. Dale",22,"libero.est.congue@blanditNam.edu"),(21,"Iliana W. Lyons",105,"enim.Etiam.imperdiet@Morbiaccumsanlaoreet.edu"),(22,"Ronan S. Chen",41,"tellus@ametnullaDonec.co.uk"),(23,"Celeste X. Gillespie",30,"tincidunt.adipiscing@velit.edu"),(24,"Brent M. Watts",45,"eget.volutpat.ornare@sapienNunc.ca");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (25,"Sopoline Burton",50,"imperdiet.ullamcorper@urnasuscipit.net"),(26,"Hadassah Solis",27,"imperdiet.non.vestibulum@nasceturridiculusmus.co.uk"),(27,"Tatum Webster",34,"libero.nec@magnaDuis.net"),(28,"Selma Valdez",28,"libero.et.tristique@Suspendissealiquetsem.ca"),(29,"Scarlet Joyce",38,"libero.at.auctor@arcuVestibulumante.co.uk"),(30,"Baker H. Fernandez",98,"Nulla@luctuset.co.uk"),(31,"Dieter Sanford",80,"molestie.arcu@arcuVivamus.ca"),(32,"Indira Simmons",58,"massa@Phasellusfermentumconvallis.co.uk"),(33,"Vance Hanson",42,"ullamcorper.eu@pretiumaliquet.ca"),(34,"Fleur Oneill",46,"scelerisque.neque@nulla.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (35,"Hermione Hatfield",83,"massa@urnajusto.edu"),(36,"Jacob L. Lowe",73,"venenatis.lacus.Etiam@Maecenasmi.org"),(37,"Asher Gilmore",51,"lorem.semper.auctor@bibendum.org"),(38,"Brett B. Lancaster",21,"Integer@ipsumDonecsollicitudin.ca"),(39,"Jocelyn Burns",78,"tempus@Nunclaoreetlectus.ca"),(40,"Cade Baker",58,"consectetuer.cursus@luctuset.net"),(41,"Jennifer Leon",84,"consequat@luctusetultrices.net"),(42,"Rama J. Pierce",91,"orci.tincidunt.adipiscing@Integer.com"),(43,"Emmanuel I. Crawford",27,"Vivamus.nibh.dolor@commodo.co.uk"),(44,"Joseph Mejia",54,"Morbi.vehicula@Suspendissecommodo.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (45,"Chancellor L. Coleman",27,"vitae.erat@ascelerisque.co.uk"),(46,"Ahmed H. Warren",52,"commodo.hendrerit.Donec@magna.org"),(47,"Reece A. Brooks",94,"Cras@risus.co.uk"),(48,"Rashad Solomon",81,"at.augue@Sed.co.uk"),(49,"Eden Mcbride",108,"enim.Nunc@ligula.org"),(50,"Angelica Mckenzie",76,"Lorem@duiaugue.co.uk"),(51,"Jarrod M. Peck",20,"dictum@pedeCumsociis.ca"),(52,"Nigel Stafford",32,"auctor.quis@ategestasa.co.uk"),(53,"Alexandra N. Woods",108,"Etiam@consectetueripsumnunc.org"),(54,"Tatiana Butler",99,"Morbi.neque@ultriciesornareelit.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (55,"Hasad Montgomery",64,"Vestibulum@utcursus.ca"),(56,"Martina Middleton",97,"Donec.feugiat.metus@quistristique.org"),(57,"Wesley Stephens",78,"quam@sociisnatoque.edu"),(58,"Stella Cortez",94,"nec@eu.com"),(59,"August Reynolds",77,"faucibus.leo.in@erosNam.com"),(60,"Flynn Newton",46,"ac.facilisis@vehicula.ca"),(61,"Avram W. King",34,"pharetra@tinciduntvehicularisus.co.uk"),(62,"Steel V. Bird",41,"orci@egetmollislectus.com"),(63,"Athena G. Glover",105,"malesuada.augue@nullaIntegervulputate.org"),(64,"Cara Dodson",34,"cursus@molestietortor.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (65,"Vielka Y. Salazar",96,"turpis.non.enim@fringillaporttitor.co.uk"),(66,"Zoe E. Hale",70,"Aliquam.adipiscing.lobortis@Phasellus.net"),(67,"Katell Pittman",36,"egestas.a@amet.edu"),(68,"Rigel Q. Lester",24,"sollicitudin.commodo@Aliquamadipiscinglobortis.co.uk"),(69,"Zephania Boyer",28,"luctus.et@luctuset.org"),(70,"Arden Weiss",63,"Donec@Sed.co.uk"),(71,"Colleen Q. Gill",99,"id.risus@Nullaeget.edu"),(72,"Athena U. Townsend",39,"nec.cursus@utmiDuis.ca"),(73,"Chase Castro",95,"faucibus@posuere.co.uk"),(74,"Brock G. Strickland",61,"neque.pellentesque@sitamet.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (75,"Magee Miles",50,"non.lobortis.quis@egetmetus.edu"),(76,"Avram N. Crosby",70,"ut@elementum.ca"),(77,"Adara Decker",30,"non.sollicitudin@doloregestasrhoncus.org"),(78,"Kato I. Hudson",101,"urna.Ut.tincidunt@ametfaucibusut.edu"),(79,"Garth A. Sampson",45,"dignissim@Sedeunibh.org"),(80,"Lareina Potter",65,"mauris.rhoncus@interdumCurabiturdictum.org"),(81,"Hayes X. Frank",87,"Lorem.ipsum.dolor@Maurismolestiepharetra.co.uk"),(82,"Slade Z. Decker",39,"in@Nullamlobortis.com"),(83,"Ariana Joyce",44,"iaculis.nec.eleifend@arcuiaculis.com"),(84,"Idola R. Craig",19,"dolor.sit@in.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (85,"Alec N. Garner",106,"a@fringillacursus.co.uk"),(86,"Jack Ingram",78,"est.ac.mattis@velitPellentesqueultricies.net"),(87,"Teegan Ashley",19,"luctus.et@cursusaenim.com"),(88,"Bianca Dodson",84,"vitae.odio.sagittis@Morbi.co.uk"),(89,"Jana Briggs",20,"scelerisque.sed@ligula.co.uk"),(90,"Mason Sheppard",38,"Morbi.metus.Vivamus@parturient.net"),(91,"Risa E. Vazquez",99,"pretium.neque@tincidunt.net"),(92,"Doris Malone",99,"fames.ac@euturpis.com"),(93,"Aspen Nolan",93,"egestas.Fusce@aliquetodio.edu"),(94,"Chaney E. Floyd",54,"sem.magna@eratvel.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (95,"Mercedes Norton",92,"erat.vitae@Suspendissealiquet.org"),(96,"Sheila Kidd",80,"Lorem.ipsum.dolor@odioPhasellus.edu"),(97,"Harding T. Vargas",56,"Maecenas.ornare@sollicitudincommodoipsum.ca"),(98,"Leroy Ferguson",41,"semper@eleifend.com"),(99,"Susan W. Ochoa",73,"neque.vitae@Nullatempor.edu"),(100,"Fuller A. Holder",99,"Maecenas@Inornare.org"),(101,"Joy Arnold",91,"malesuada@accumsan.co.uk"),(102,"Russell Flowers",45,"elit@libero.ca"),(103,"Quinlan N. Leon",31,"in.magna@magnanecquam.org"),(104,"Charles X. Saunders",94,"commodo@tempus.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (105,"Roth U. Bush",38,"dis.parturient.montes@eteuismodet.com"),(106,"Hayfa Figueroa",69,"egestas@sodales.edu"),(107,"Karina Boyer",34,"at.fringilla.purus@vitaepurus.net"),(108,"Vincent Glenn",70,"blandit.enim@volutpatNulladignissim.ca"),(109,"Summer X. Figueroa",47,"lacus@Vestibulum.org"),(110,"Grady S. Fields",59,"eu.neque.pellentesque@anteipsum.com"),(111,"Joseph S. Becker",91,"enim@cursusdiam.ca"),(112,"Hammett I. Patrick",88,"lacus@anteipsumprimis.co.uk"),(113,"Alea E. Washington",87,"sit.amet.consectetuer@nonmagnaNam.edu"),(114,"Patrick E. William",44,"non@Fuscemollis.edu");


INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (115,"Reese Walsh",21,"rutrum.magna.Cras@tinciduntdui.edu"),(116,"Beck Hurley",29,"vitae@pedemalesuadavel.com"),(117,"Simon I. Zamora",91,"consectetuer.adipiscing.elit@duisemperet.com"),(118,"Jaquelyn Pope",18,"id@aclibero.edu"),(119,"Vladimir P. Jenkins",42,"ornare.Fusce@placeratorci.co.uk"),(120,"Chastity I. Gaines",43,"Cras@ornarelectus.org"),(121,"Cruz Sanchez",61,"nisl.elementum@ametrisus.com"),(122,"Savannah U. Mcgowan",109,"tempor.diam@Nuncsed.edu"),(123,"Brent Workman",49,"fames@Phasellusvitae.net"),(124,"Frances Holman",29,"lorem.ut.aliquam@nuncinterdum.ca");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (125,"Orlando X. Calderon",91,"amet@tincidunt.ca"),(126,"Amelia W. Walters",61,"iaculis@lacusEtiambibendum.ca"),(127,"Nola Craft",51,"rutrum.justo@convallisincursus.ca"),(128,"Clayton Spencer",104,"Class.aptent@euenim.com"),(129,"Althea Quinn",107,"sed.libero@dictum.ca"),(130,"Cedric T. Mccall",59,"ut.nisi.a@adipiscingenimmi.net"),(131,"Kiayada Bentley",47,"arcu.Morbi@rutrumnonhendrerit.org"),(132,"Salvador V. Leach",100,"ligula@Morbisitamet.edu"),(133,"Bethany Waters",41,"nulla@eros.edu"),(134,"Lars F. Randall",59,"accumsan.interdum.libero@ipsumprimis.ca");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (135,"Charissa B. Larsen",95,"orci@tempordiamdictum.edu"),(136,"Shafira Love",86,"velit.eget.laoreet@gravida.edu"),(137,"Jin U. Mcdaniel",45,"Integer.eu@nascetur.ca"),(138,"Silas X. Spencer",29,"eu@aliquet.ca"),(139,"Oscar Mcfarland",74,"sodales@maurisIntegersem.co.uk"),(140,"Gage Young",22,"Cras@vestibulumMaurismagna.co.uk"),(141,"Melissa Carpenter",66,"congue.In.scelerisque@lorem.co.uk"),(142,"Dolan Kramer",110,"dictum.mi.ac@Morbinon.edu"),(143,"Nevada Reeves",68,"a.nunc.In@velnisl.co.uk"),(144,"Channing Wells",74,"non.feugiat@idrisus.ca");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (145,"Mohammad Hatfield",64,"convallis.ante.lectus@Vestibulumaccumsan.org"),(146,"Hadley Velazquez",88,"imperdiet.non.vestibulum@necleo.co.uk"),(147,"Amelia Barnes",70,"Quisque.ac@senectus.ca"),(148,"Colton Kelley",40,"purus.Nullam.scelerisque@magnaPhasellus.ca"),(149,"Bethany Carroll",67,"lorem@Nullatinciduntneque.ca"),(150,"Ahmed M. Ewing",77,"orci@ullamcorperDuiscursus.com"),(151,"Maite Hughes",45,"at@senectus.edu"),(152,"Kimberley N. Levine",92,"non.cursus.non@gravidasitamet.edu"),(153,"Dai Holmes",54,"nonummy@vestibulummassarutrum.ca"),(154,"April L. Carter",58,"ipsum.primis@etipsum.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (155,"Rhoda O. Boone",53,"aliquet.metus@quam.ca"),(156,"Chanda Clayton",19,"Aliquam.adipiscing@Phasellusvitae.ca"),(157,"Rana O. Prince",47,"nibh@egestasFusce.ca"),(158,"Anastasia R. Espinoza",20,"fringilla.cursus.purus@miDuisrisus.net"),(159,"Candace Larson",66,"dui@diamnuncullamcorper.ca"),(160,"Fulton Bradshaw",39,"tincidunt.adipiscing@magnanec.net"),(161,"Bree F. Travis",90,"mauris.ut@purusin.co.uk"),(162,"Joshua Talley",71,"et.ultrices.posuere@liberoet.org"),(163,"Dominic Zamora",104,"Nam@Crassedleo.co.uk"),(164,"Abdul Riley",22,"natoque@tincidunt.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (165,"Georgia O. Burgess",79,"luctus.sit.amet@quam.net"),(166,"Ruby J. Price",43,"Etiam@Aliquameratvolutpat.edu"),(167,"Grant G. Valencia",23,"scelerisque@nuncnulla.co.uk"),(168,"Fritz Jimenez",107,"blandit.Nam@dapibusgravida.ca"),(169,"Lenore Hart",24,"semper.auctor.Mauris@Utnec.com"),(170,"Duncan J. Oneal",79,"arcu.Curabitur@Quisqueporttitoreros.ca"),(171,"Leo W. Hill",37,"et.magnis.dis@nunc.ca"),(172,"Carla Bolton",56,"magna@dignissim.net"),(173,"Yetta Warner",78,"sem.elit@mi.org"),(174,"Brent Padilla",55,"eleifend.vitae@MaurisnullaInteger.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (175,"Dieter Delgado",34,"eget@augue.com"),(176,"Vera X. Schultz",46,"mattis.Cras@orciconsectetuereuismod.org"),(177,"Leila J. Hodge",100,"Cras.dictum@elitafeugiat.co.uk"),(178,"Dane X. Moreno",99,"montes@tellusid.edu"),(179,"Byron B. Roach",39,"lacinia.mattis@leoelementum.org"),(180,"Jelani Torres",37,"neque.sed@ut.co.uk"),(181,"Clare G. Massey",106,"Aliquam@nullaante.org"),(182,"Gabriel V. Sykes",99,"Cras.pellentesque@mauris.org"),(183,"Timon Callahan",67,"ac.ipsum@In.edu"),(184,"Petra O. Jones",89,"tempor@Praesentluctus.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (185,"Cathleen H. Chase",62,"Nunc@nuncacmattis.com"),(186,"Aurelia V. Bradford",91,"purus.accumsan@odioNaminterdum.org"),(187,"Marny L. Mack",26,"dignissim.pharetra.Nam@arcuCurabitur.com"),(188,"Nash Crosby",28,"orci@mauris.net"),(189,"Dacey P. Sellers",92,"nunc.ullamcorper.eu@turpis.ca"),(190,"Hiram Y. Reeves",39,"natoque@afelis.ca"),(191,"Oren B. Forbes",83,"leo@interdumfeugiat.net"),(192,"Meredith P. Parrish",95,"rutrum.urna.nec@Fusce.edu"),(193,"Wang Lowery",73,"mauris@miacmattis.com"),(194,"Raya Davidson",101,"et.malesuada@sitamet.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (195,"Emily Joseph",35,"magna.malesuada.vel@magna.org"),(196,"Zahir Warren",91,"Sed@tinciduntaliquam.co.uk"),(197,"Ciara White",20,"at.auctor@etmalesuada.ca"),(198,"Rylee K. Bradshaw",78,"sem.semper.erat@sedtortor.edu"),(199,"Kirsten G. Woodard",106,"Aenean@consequatlectussit.edu"),(200,"Tamekah J. Evans",72,"Cras.dolor.dolor@ridiculus.net"),(201,"Aristotle V. Aguirre",102,"aliquam.adipiscing@eget.ca"),(202,"Francis A. Roach",87,"Mauris@ProinmiAliquam.ca"),(203,"Joseph T. Stephens",90,"enim.gravida@ad.net"),(204,"Leilani Melendez",78,"et.arcu@dignissimlacusAliquam.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (205,"Hunter Day",106,"et.pede@mattisIntegereu.com"),(206,"Fiona A. Merrill",43,"purus.sapien@Maurisblanditenim.co.uk"),(207,"Joshua E. Burnett",89,"rutrum.magna@ornareegestasligula.ca"),(208,"Suki Q. Sykes",100,"erat@nonsapien.ca"),(209,"Peter K. Spence",107,"nascetur.ridiculus.mus@at.org"),(210,"Aristotle P. Willis",73,"eget@convallisdolor.edu"),(211,"Lance Gamble",20,"Suspendisse.ac@fringillaDonecfeugiat.org"),(212,"Solomon I. Flynn",89,"facilisis.lorem.tristique@Nam.net"),(213,"Paloma Kramer",31,"at.auctor.ullamcorper@erat.ca"),(214,"Anthony Dickerson",61,"rhoncus@risusodio.co.uk");

INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (215,"Rae A. Blevins",67,"pellentesque@semper.org"),(216,"Honorato F. Stanley",22,"odio.sagittis@egestasFusce.edu"),(217,"Justine Davenport",52,"Quisque.libero.lacus@gravidamauris.ca"),(218,"Kermit Reynolds",33,"arcu.Nunc.mauris@semNullainterdum.org"),(219,"Yuri Ewing",22,"Aliquam@loremtristique.co.uk"),(220,"Brett R. Rodriquez",27,"lectus.convallis@cursusdiam.org"),(221,"Mason V. Case",103,"urna.justo@Quisquelibero.com"),(222,"Winifred T. Shaffer",92,"tincidunt.nunc@pedeCumsociis.org"),(223,"Lysandra Henderson",101,"non@Maurisquisturpis.net"),(224,"Alec Velez",103,"magnis@nuncsed.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (225,"Keiko Mccullough",49,"mauris@disparturientmontes.edu"),(226,"Stacy D. Eaton",27,"tincidunt.pede@Inmi.ca"),(227,"Kenyon Cote",84,"interdum.Curabitur.dictum@vulputateullamcorper.net"),(228,"Peter Rodgers",50,"neque@lacusQuisqueimperdiet.edu"),(229,"Laurel B. Becker",76,"vitae@Praesentinterdumligula.co.uk"),(230,"Anika V. Callahan",19,"eros.turpis@enimMaurisquis.org"),(231,"Ayanna V. Wilson",58,"mus.Proin.vel@rutrummagna.net"),(232,"Oliver Wheeler",110,"et.ultrices@nislMaecenasmalesuada.org"),(233,"James S. Noble",66,"neque.tellus@anteblandit.co.uk"),(234,"Daryl W. Hogan",102,"cursus.a@consectetueripsumnunc.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (235,"Zia R. Marks",77,"imperdiet.erat@pede.com"),(236,"Carolyn F. Goff",55,"augue.Sed.molestie@dui.edu"),(237,"Cathleen Smith",104,"morbi.tristique.senectus@eleifendnunc.org"),(238,"Cecilia Erickson",80,"Aenean.eget.magna@nibhvulputate.net"),(239,"Reagan R. Johnston",28,"lorem@vulputateeu.com"),(240,"Blaze K. Johnston",95,"orci.Phasellus.dapibus@mienimcondimentum.edu"),(241,"Nash Cleveland",34,"ridiculus@Maecenasiaculis.com"),(242,"Hall Kline",78,"malesuada@mauris.net"),(243,"Jasmine V. Kennedy",47,"est.ac@gravida.ca"),(244,"Amena Mcdonald",45,"enim.condimentum@Etiam.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (245,"Maggy S. Gray",56,"Vivamus.non@Aliquam.net"),(246,"Mary O. Lynch",86,"erat.Vivamus.nisi@scelerisquesed.edu"),(247,"Zorita Thompson",81,"sed@posuereatvelit.co.uk"),(248,"Beau Valdez",54,"mauris.ipsum@egetlacusMauris.net"),(249,"Colorado T. Sanchez",62,"purus.ac@utpharetrased.net"),(250,"Jermaine F. Dodson",27,"a.sollicitudin@consequatenimdiam.com"),(251,"Kaye V. Black",107,"Maecenas.ornare.egestas@Sed.net"),(252,"Hiram M. Marshall",33,"vel.est@Namporttitorscelerisque.ca"),(253,"Aubrey E. Wolf",81,"dictum.mi.ac@interdumliberodui.org"),(254,"Keefe W. Vance",19,"mollis@Cras.ca");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (255,"Abra G. Grimes",28,"a.feugiat.tellus@Praesentluctus.org"),(256,"Nasim Hopkins",47,"non@adipiscingnonluctus.edu"),(257,"Freya Albert",90,"amet.consectetuer@libero.edu"),(258,"Rudyard Barnett",101,"enim.gravida.sit@massanon.com"),(259,"Nolan Short",90,"Nullam.ut.nisi@Proin.org"),(260,"Abel H. Mclaughlin",71,"adipiscing@nibh.net"),(261,"Mollie George",53,"varius.et.euismod@Phasellusvitaemauris.co.uk"),(262,"Barry Y. Sutton",31,"consectetuer.mauris.id@sollicitudincommodoipsum.com"),(263,"Illiana A. Blanchard",105,"justo.nec.ante@magna.org"),(264,"Zeph Bolton",102,"eu.dolor.egestas@Utsagittis.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (265,"Rose E. Cleveland",39,"consectetuer.adipiscing@eudolor.edu"),(266,"Hu Madden",34,"cursus.luctus@duiFusce.edu"),(267,"Ulysses Ochoa",32,"vitae.erat.Vivamus@arcuac.ca"),(268,"Rudyard Harrington",41,"Mauris@odio.edu"),(269,"Alea Q. Hines",82,"nibh.dolor@euismodindolor.ca"),(270,"Dexter Cooke",25,"fames@aptenttacitisociosqu.com"),(271,"Ferdinand W. Donovan",51,"ullamcorper.Duis.cursus@semper.edu"),(272,"Baxter Kline",37,"at@euerosNam.ca"),(273,"Bree Clark",27,"tristique@pharetrased.co.uk"),(274,"Brynn Harris",66,"Sed.dictum@posuerecubilia.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (275,"Tyrone Q. Barker",75,"dui@euultrices.com"),(276,"Kennan M. James",96,"pellentesque.Sed.dictum@Nuncpulvinararcu.ca"),(277,"Wang Sweet",69,"scelerisque.dui@Nunc.edu"),(278,"Kaitlin P. Chandler",28,"eu.dui@sitamet.edu"),(279,"Allen Mckinney",48,"dui.augue@tellusnonmagna.net"),(280,"Cedric H. Riley",34,"sodales.at.velit@vulputatevelit.net"),(281,"Ainsley M. Trujillo",99,"Fusce.feugiat@diam.org"),(282,"Gage Gordon",53,"elit@bibendumDonecfelis.net"),(283,"Emery I. Bradford",40,"hymenaeos.Mauris@lacusvarius.com"),(284,"Keane I. Hunter",105,"sagittis@magnaatortor.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (285,"Jasper Tyler",19,"Aliquam.ornare@blanditcongueIn.co.uk"),(286,"Jennifer O. Lane",18,"penatibus.et@fringilla.com"),(287,"Lynn N. Mcmahon",67,"Suspendisse.aliquet@metus.org"),(288,"Jocelyn Levy",19,"velit.eu@adipiscing.ca"),(289,"Seth Miles",58,"Morbi.non.sapien@diamvelarcu.com"),(290,"Zenaida French",51,"tempor.bibendum.Donec@Fuscedolorquam.ca"),(291,"Heather H. Gilliam",63,"velit.in@temporbibendumDonec.co.uk"),(292,"Yael Cantrell",101,"aliquet.metus@afelis.org"),(293,"Colby H. Jones",54,"sit@fermentum.edu"),(294,"Pascale W. Leon",95,"ipsum.Phasellus@vitae.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (295,"Fulton Cross",91,"malesuada@arcu.ca"),(296,"Grady P. Kelly",60,"Duis.at.lacus@aliquam.net"),(297,"Kennedy D. Hays",29,"lacinia@arcuvel.net"),(298,"Hollee M. Church",76,"Aenean@dui.edu"),(299,"Justina M. Mcleod",66,"Ut.semper.pretium@eratnonummy.org"),(300,"Deacon Roman",23,"ligula.Donec@lacus.co.uk"),(301,"Dennis Bean",36,"tempus.lorem@ante.co.uk"),(302,"Kalia X. Mcmillan",54,"non.cursus.non@egestasFusce.org"),(303,"Hu Hutchinson",65,"nonummy.ut.molestie@Morbi.com"),(304,"Robin H. Robertson",54,"a.nunc.In@nibh.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (305,"Carson Mcclure",41,"eget.volutpat@risusQuisque.co.uk"),(306,"Cole K. Vasquez",93,"Proin@estMauris.ca"),(307,"Cassidy N. Mccall",97,"Sed.eu@iaculisodio.ca"),(308,"Valentine Kim",45,"laoreet@anteipsum.co.uk"),(309,"Steel Doyle",28,"arcu@convallisligulaDonec.edu"),(310,"Nigel Tanner",44,"dui.semper@scelerisquemollisPhasellus.edu"),(311,"Emi Perez",41,"orci.lobortis@vulputate.com"),(312,"Steel Hodges",85,"mus.Proin.vel@euodio.edu"),(313,"Sharon Evans",34,"metus@mattis.net"),(314,"Buffy Rosario",29,"gravida.mauris@urna.edu");

INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (315,"Lillian Ward",65,"non@loremeget.ca"),(316,"Grace Y. Newton",106,"arcu@Aenean.ca"),(317,"Mariam I. Delacruz",38,"nibh.Phasellus.nulla@faucibusorci.net"),(318,"Lucas L. Bolton",50,"magna@nasceturridiculusmus.co.uk"),(319,"Urielle Reilly",87,"nisi.Aenean@semperauctorMauris.org"),(320,"Zahir N. Oneil",26,"mauris.rhoncus.id@Suspendisse.ca"),(321,"Hannah R. Erickson",19,"magna@diam.com"),(322,"Alexis Chen",60,"venenatis.vel.faucibus@atrisus.edu"),(323,"Rebecca Holden",42,"neque.In.ornare@Nullamut.org"),(324,"Allen Delgado",72,"dapibus.gravida@leo.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (325,"Lani F. Francis",34,"cubilia.Curae@aliquetvel.com"),(326,"Ivana X. Burch",68,"In@magnaCrasconvallis.com"),(327,"Fleur Christensen",94,"dis@et.org"),(328,"Davis R. Luna",78,"libero.est.congue@lectusNullamsuscipit.edu"),(329,"Claudia S. Chan",64,"dolor@Maurisvestibulumneque.edu"),(330,"Rana K. Townsend",62,"at.velit.Pellentesque@purussapiengravida.edu"),(331,"Chester Sexton",73,"ante.dictum.mi@arcuVivamussit.edu"),(332,"Xander Mcbride",28,"vestibulum.neque.sed@vitae.edu"),(333,"Mufutau Jimenez",99,"enim@eros.co.uk"),(334,"Melissa Jordan",106,"natoque.penatibus.et@consequatpurusMaecenas.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (335,"Ralph M. Finley",47,"sem.molestie.sodales@sodalesnisi.com"),(336,"Jael Gilliam",22,"turpis@Suspendisseseddolor.co.uk"),(337,"Hu Gallagher",96,"nisi.dictum@ligulaconsectetuer.edu"),(338,"Arden D. Kelly",54,"purus.Maecenas@justo.co.uk"),(339,"Hiram A. Sellers",94,"Ut@Vivamus.co.uk"),(340,"Stone L. Nieves",46,"sem@massanonante.edu"),(341,"Dawn Z. David",25,"aliquet.sem.ut@Maurisblanditenim.co.uk"),(342,"Brent T. Guzman",96,"ad.litora@dolor.org"),(343,"Josephine H. Donovan",81,"enim@eueratsemper.org"),(344,"Flynn P. Wynn",110,"aliquam.eros@gravidasit.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (345,"Branden Jackson",65,"ut.pellentesque.eget@urnaet.net"),(346,"Yardley Reid",44,"ultrices.Duis.volutpat@elementumloremut.co.uk"),(347,"Yeo Goodwin",74,"Nunc@Fusce.net"),(348,"Azalia Ward",81,"adipiscing@temporest.net"),(349,"Adele Roach",82,"posuere.at@gravida.co.uk"),(350,"Myra Brennan",82,"Duis@Etiam.net"),(351,"Blaze Mendoza",67,"malesuada@turpis.co.uk"),(352,"Channing V. Bean",53,"semper.auctor.Mauris@bibendum.org"),(353,"Nathan Tyler",79,"sed.est@velitAliquam.net"),(354,"Lavinia G. Edwards",61,"lacus.Aliquam@cursus.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (355,"Dante Melton",55,"aliquam.adipiscing@montesnascetur.org"),(356,"Cassandra L. Lucas",41,"quam.elementum.at@interdumfeugiat.net"),(357,"Graham Faulkner",75,"Cras.vulputate.velit@Fusce.com"),(358,"Jasper V. Dejesus",102,"et.ipsum@imperdiet.net"),(359,"Uma U. Mayo",72,"volutpat.ornare.facilisis@ligulaNullamfeugiat.net"),(360,"Daria Griffin",33,"Etiam.gravida.molestie@loremipsumsodales.net"),(361,"Yoshio O. Duffy",83,"amet.ornare@nonluctussit.edu"),(362,"Brett S. Nixon",92,"rhoncus.Proin@leo.ca"),(363,"Ezra Castro",35,"lacinia@blandit.ca"),(364,"Arden Carlson",23,"dui.lectus.rutrum@ut.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (365,"Brennan Hodge",46,"mollis.non.cursus@IntegerurnaVivamus.com"),(366,"Ivy A. Morin",110,"Nunc@telluseuaugue.com"),(367,"Gail Bond",84,"faucibus@lobortismaurisSuspendisse.org"),(368,"Merrill Hendrix",40,"ut@magnisdis.org"),(369,"Hoyt Daugherty",57,"quis.turpis@veliteusem.org"),(370,"Devin Delaney",73,"Suspendisse.tristique.neque@quisurna.com"),(371,"Erich Dudley",61,"cursus.vestibulum.Mauris@et.edu"),(372,"Leah M. Nielsen",36,"justo.nec.ante@Donecnon.org"),(373,"Cherokee Z. Chen",100,"mauris@Suspendissetristiqueneque.org"),(374,"Hope Farrell",33,"Integer.in.magna@etpedeNunc.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (375,"Anika J. Gamble",95,"et@pellentesquemassalobortis.edu"),(376,"Briar Hawkins",31,"cursus.vestibulum@Morbi.com"),(377,"Daquan C. Miles",44,"Aenean.euismod.mauris@nibh.org"),(378,"Tyler Hopper",109,"eu.arcu.Morbi@pulvinararcuet.net"),(379,"Ingrid Golden",28,"sem@facilisiSed.co.uk"),(380,"Jonas Stephens",72,"commodo@lobortisultrices.com"),(381,"Castor G. Hunter",29,"sociis.natoque@diamPellentesque.com"),(382,"Shoshana L. Davenport",84,"ornare@euismodenim.org"),(383,"Rhona Richard",95,"tempus.risus.Donec@sapienNuncpulvinar.edu"),(384,"Ruby Y. Manning",57,"sed.tortor@feugiatLorem.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (385,"Fiona Dalton",26,"nonummy.ultricies@eutelluseu.ca"),(386,"Galvin Dudley",63,"tellus.Aenean.egestas@hendreritneque.net"),(387,"Randall N. Marks",40,"diam.nunc.ullamcorper@eget.edu"),(388,"Genevieve Guzman",57,"non.nisi.Aenean@egestasurnajusto.edu"),(389,"Miranda U. Greene",93,"Fusce.dolor@fringilla.co.uk"),(390,"Kevyn Tucker",37,"magna@accumsaninterdum.co.uk"),(391,"Brittany Barry",101,"ipsum.dolor.sit@duiCumsociis.org"),(392,"Marvin Marks",46,"leo.Vivamus@sitamet.org"),(393,"Gillian P. Austin",107,"Maecenas.malesuada@lacus.edu"),(394,"Lionel Rojas",33,"pede.blandit@lectussitamet.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (395,"Amity A. Mcbride",100,"parturient.montes.nascetur@metus.ca"),(396,"Harrison S. Harvey",47,"ante@ligula.co.uk"),(397,"Avram Peterson",18,"sagittis.placerat.Cras@viverraDonec.net"),(398,"Imogene Q. Buck",36,"arcu.Vestibulum.ut@Suspendisse.edu"),(399,"Stewart H. Crosby",82,"nunc@eu.ca"),(400,"Dennis M. Mcneil",98,"et.malesuada.fames@posuerecubiliaCurae.org"),(401,"Paula Gomez",78,"pellentesque.tellus@Suspendisseacmetus.net"),(402,"Igor W. Moss",100,"dapibus@estNunc.edu"),(403,"Debra Serrano",110,"ornare.egestas.ligula@suscipitnonummy.com"),(404,"Paki H. Bray",73,"Nullam.ut.nisi@CrasinterdumNunc.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (405,"Kelsie Schmidt",110,"sed.pede.nec@sitametante.com"),(406,"Ahmed Harding",91,"nulla.vulputate@lacusUtnec.ca"),(407,"Bruce Lopez",90,"interdum.ligula.eu@sedconsequatauctor.edu"),(408,"Wing K. Hendrix",108,"lectus.sit.amet@tinciduntduiaugue.edu"),(409,"Maite A. Pate",109,"orci.lobortis@elitNullafacilisi.edu"),(410,"Reese C. Goff",93,"Maecenas@acturpis.ca"),(411,"Maggy M. Perez",57,"Quisque.varius@Nam.com"),(412,"Caleb I. Sexton",104,"mus.Proin.vel@metus.org"),(413,"Knox J. Glenn",99,"rutrum@id.net"),(414,"Marcia Bird",65,"iaculis@pede.org");

INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (415,"Anastasia E. Stephenson",75,"Vivamus.nisi.Mauris@ultricesDuis.net"),(416,"Jordan A. Walton",44,"dolor@Nullam.org"),(417,"Armando A. Dyer",45,"Morbi.sit@commodoauctor.ca"),(418,"Ferris I. May",43,"fames.ac@liberoInteger.net"),(419,"Phelan Q. Avery",77,"Donec.fringilla.Donec@intempus.edu"),(420,"Libby I. Patel",86,"feugiat@posuere.net"),(421,"Mollie Cantu",20,"lacus.Ut@sociisnatoque.co.uk"),(422,"Linda A. Golden",105,"a@bibendumsed.edu"),(423,"Hedwig Lawrence",92,"nascetur.ridiculus@tincidunt.co.uk"),(424,"Rana Benton",73,"primis.in.faucibus@atpede.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (425,"Cally J. Rasmussen",22,"sit.amet@lobortisultricesVivamus.co.uk"),(426,"Kennedy Donaldson",90,"sed@condimentumegetvolutpat.ca"),(427,"Joel Andrews",108,"venenatis.lacus@eu.org"),(428,"Donna E. Noel",80,"diam.at@etmalesuadafames.net"),(429,"Eliana Callahan",88,"cubilia.Curae.Donec@ut.net"),(430,"Aubrey L. Mclean",67,"eget.tincidunt.dui@vulputaterisus.net"),(431,"Chester Mercado",64,"egestas.urna@antebibendum.co.uk"),(432,"Geraldine Q. Hull",22,"Curabitur@rutrum.edu"),(433,"Shannon C. Stevenson",72,"imperdiet@Sedmolestie.net"),(434,"Rigel Houston",78,"ac.libero@noncursusnon.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (435,"Joelle House",40,"eget.lacus@acmetus.com"),(436,"Arsenio L. Cannon",48,"sed.pede.Cum@placeratvelitQuisque.ca"),(437,"Theodore Guy",60,"tellus@viverraMaecenas.net"),(438,"Mufutau F. Walls",106,"odio.sagittis.semper@nonhendrerit.ca"),(439,"Frances Mosley",99,"dolor.tempus@molestietellus.org"),(440,"Simon R. Bartlett",23,"elit@Proin.edu"),(441,"Noelle V. Moreno",95,"ipsum@etmagnisdis.ca"),(442,"Garth V. Todd",44,"sapien@purusmaurisa.net"),(443,"Courtney I. Abbott",68,"odio.auctor.vitae@Nunc.ca"),(444,"Aubrey England",38,"amet@Donecnibh.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (445,"Kasimir Gray",72,"varius@ornareelitelit.co.uk"),(446,"Natalie H. Sexton",36,"sed@bibendumsed.edu"),(447,"Irma Short",107,"ridiculus@Aliquam.com"),(448,"Perry S. Fitzgerald",100,"purus.Maecenas.libero@eget.edu"),(449,"Oleg David",54,"rutrum.Fusce.dolor@Sednullaante.net"),(450,"Beck Walker",20,"elementum@semutdolor.net"),(451,"Adrian Noble",53,"semper@semper.com"),(452,"Colby O. Greer",45,"malesuada.fames.ac@orciin.org"),(453,"Galena S. Suarez",92,"odio.semper.cursus@miDuis.org"),(454,"Denton Wallace",77,"a@metus.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (455,"Beck U. Morse",22,"sem.semper@ante.org"),(456,"Tatyana Ochoa",75,"pellentesque.Sed.dictum@ac.org"),(457,"Colin Herring",70,"erat.Sed.nunc@libero.com"),(458,"Cameron Solomon",34,"sit.amet@justo.org"),(459,"Jonah Durham",18,"erat.Etiam.vestibulum@consectetuer.com"),(460,"Chase M. Wells",55,"in.dolor.Fusce@tellussem.ca"),(461,"Imelda G. Charles",76,"sit.amet.metus@nisl.com"),(462,"Ignacia U. Park",86,"odio.a.purus@lobortisClass.org"),(463,"Haley Tate",28,"posuere.vulputate.lacus@convallisligula.ca"),(464,"Willa M. Stein",27,"orci.Ut.semper@rhoncusDonecest.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (465,"Rafael U. Mercado",88,"eros.turpis.non@eudui.co.uk"),(466,"Dieter W. Drake",107,"augue@vitaedolorDonec.com"),(467,"Alec K. Chambers",40,"dictum@senectusetnetus.edu"),(468,"Alvin Orr",54,"et.magnis@auctornonfeugiat.edu"),(469,"Beck Rosales",91,"enim@ipsumPhasellus.ca"),(470,"Shaine V. Glover",107,"elit.Aliquam@ProinultricesDuis.net"),(471,"Wang F. Velez",94,"diam@ullamcorperviverra.edu"),(472,"Adrian K. Fuller",53,"Aliquam.tincidunt.nunc@vulputatevelit.com"),(473,"Kelly Q. Weiss",26,"sapien.molestie.orci@nisiMaurisnulla.co.uk"),(474,"Virginia Rowe",68,"convallis@dapibusquam.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (475,"Regina V. Douglas",30,"Morbi.metus@Quisque.co.uk"),(476,"Sade Mason",42,"faucibus@pharetra.org"),(477,"Madaline E. Hensley",100,"Quisque.fringilla@vehicula.ca"),(478,"Jana W. Durham",35,"egestas.nunc.sed@Phasellusfermentum.ca"),(479,"Noah Briggs",59,"facilisis.non@semegetmassa.com"),(480,"Honorato I. Robbins",74,"pharetra@nibhPhasellus.net"),(481,"Ira I. Stevens",33,"vitae.dolor@eudolor.ca"),(482,"Roth T. Singleton",41,"aliquet.Proin.velit@adipiscing.edu"),(483,"Dexter C. Park",79,"sed@pede.com"),(484,"Rhona Pearson",26,"lacus.varius@aliquamiaculis.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (485,"Uriah Bauer",84,"a.tortor.Nunc@natoquepenatibus.org"),(486,"Glenna S. Hurst",27,"volutpat@bibendumsedest.edu"),(487,"Ray F. Le",99,"ipsum.nunc@pellentesqueegetdictum.edu"),(488,"Felicia Carroll",82,"turpis.vitae.purus@arcuVivamussit.net"),(489,"Indigo Rutledge",79,"dolor.sit.amet@sed.ca"),(490,"Geraldine Beck",35,"tempor@commodoipsumSuspendisse.co.uk"),(491,"Tobias Blankenship",34,"fringilla.euismod.enim@adipiscingMauris.ca"),(492,"Delilah B. Booker",32,"convallis.in@egetmetus.org"),(493,"Ina Peterson",69,"accumsan@nuncinterdum.edu"),(494,"Linus Burns",37,"Sed.nunc.est@nonnisi.org");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (495,"Lawrence U. Glass",57,"in.magna.Phasellus@enimEtiam.edu"),(496,"Hiram Obrien",66,"elit.Curabitur.sed@ornarelibero.co.uk"),(497,"Timothy L. Rhodes",21,"blandit.enim.consequat@Quisquevarius.ca"),(498,"Austin Keller",42,"dapibus.rutrum@id.co.uk"),(499,"Julian Keith",88,"a.scelerisque@at.co.uk"),(500,"Hadassah Farley",34,"non@semper.ca"),(501,"Hedy Russell",99,"facilisis.non@nonummyacfeugiat.com"),(502,"Chancellor R. Spencer",57,"dui.lectus.rutrum@orciquislectus.co.uk"),(503,"Amber Rosario",107,"aliquam@neque.com"),(504,"Louis V. Moreno",29,"Nam@ornareplaceratorci.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (505,"Camilla N. Torres",28,"sit.amet@bibendumfermentummetus.edu"),(506,"Chancellor V. Armstrong",30,"sagittis@euismod.com"),(507,"Bruno Hooper",22,"interdum.feugiat.Sed@ametdapibusid.edu"),(508,"Courtney L. Bird",37,"neque.sed.sem@Donec.ca"),(509,"Kimberly U. Stokes",39,"nec.tempus.mauris@accumsanlaoreet.net"),(510,"Jerry Burt",100,"massa@nibhvulputate.org"),(511,"Igor Holmes",90,"nec.enim@indolorFusce.net"),(512,"Chancellor S. Douglas",42,"Fusce.aliquet@PhasellusornareFusce.net"),(513,"Erich V. Turner",95,"sed@Maurisvestibulum.ca"),(514,"Sylvester Lawson",27,"Duis.ac.arcu@a.ca");

INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (515,"Hayden Bailey",101,"tincidunt.nibh.Phasellus@montesnascetur.org"),(516,"Madeson Leon",31,"Morbi.sit.amet@nonsapien.co.uk"),(517,"Shelley Whitaker",57,"Nulla@scelerisquescelerisque.edu"),(518,"Luke Riley",88,"vestibulum@sitametrisus.net"),(519,"Jillian Cummings",98,"pede@molestietellusAenean.co.uk"),(520,"Otto Goodman",23,"euismod.mauris@vitaemaurissit.co.uk"),(521,"Isadora D. Irwin",91,"consectetuer@tristiquepellentesque.edu"),(522,"Elliott Foreman",31,"nibh@rutrum.org"),(523,"Serina H. Nieves",31,"et@arcuVestibulum.org"),(524,"Anjolie K. Gilliam",88,"tortor.dictum.eu@tellusnon.ca");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (525,"Cullen Chandler",34,"Donec@dictumeleifendnunc.co.uk"),(526,"Quin H. Carlson",40,"nunc@nonfeugiatnec.ca"),(527,"Aaron Short",34,"eu.neque.pellentesque@egestas.ca"),(528,"Leila O. Garner",68,"tincidunt.aliquam.arcu@molestieSedid.com"),(529,"Astra K. Hobbs",102,"a.ultricies.adipiscing@consectetuer.co.uk"),(530,"Hanna M. Drake",29,"non@sociis.com"),(531,"Grady X. Hancock",34,"facilisis.magna@dolornonummyac.ca"),(532,"Aileen Koch",61,"eget.ipsum.Donec@ultricesposuere.org"),(533,"Martena Beard",36,"nec@amet.net"),(534,"Castor Mclaughlin",50,"Cras.lorem.lorem@nonlacinia.net");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (535,"Britanni Herrera",94,"amet.dapibus@placerat.ca"),(536,"Flynn Cummings",82,"elit.Aliquam.auctor@odiosagittissemper.edu"),(537,"Audra Hunter",68,"Mauris@euarcuMorbi.ca"),(538,"Dean G. Lang",32,"risus@sitamet.ca"),(539,"Ryan Y. Hood",44,"mi.enim.condimentum@Vivamusmolestie.edu"),(540,"Wylie N. Clayton",44,"nulla.In.tincidunt@sociisnatoque.com"),(541,"Abraham Cantrell",42,"Nullam.feugiat.placerat@Class.net"),(542,"Kevin Terry",41,"ut.nulla.Cras@netusetmalesuada.ca"),(543,"Ariel Y. Cox",88,"consequat@diam.org"),(544,"Macy V. Delgado",99,"Ut.semper.pretium@Proinnon.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (545,"Lesley F. Higgins",96,"parturient.montes.nascetur@erat.net"),(546,"Demetrius Z. Holcomb",103,"scelerisque.dui.Suspendisse@faucibusut.com"),(547,"Joel Y. Berg",84,"massa.Integer.vitae@ametdiameu.com"),(548,"Boris M. Bridges",96,"purus.in@aliquetPhasellusfermentum.net"),(549,"Zahir V. Blevins",62,"justo@elitpharetra.com"),(550,"Gray U. Elliott",93,"Phasellus.ornare@malesuadaid.co.uk"),(551,"Angela Hunter",58,"vitae@ipsumporta.edu"),(552,"Fletcher H. Bauer",57,"eget.massa@tristiquepellentesque.net"),(553,"Anjolie Nelson",72,"Nunc.laoreet@sed.net"),(554,"Dominic W. Warren",35,"Mauris.quis.turpis@vitaepurus.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (555,"Noel Pope",44,"mi.pede.nonummy@bibendumullamcorperDuis.com"),(556,"Uma X. Landry",36,"Nam@Curabiturutodio.org"),(557,"Kristen Love",22,"montes@Donecnon.org"),(558,"Kato E. Decker",36,"ligula.Nullam.enim@maurisa.com"),(559,"Sopoline V. Koch",69,"elit@Maecenaslibero.com"),(560,"Clio Miles",101,"vulputate.posuere@nislQuisque.edu"),(561,"Barrett E. Glass",72,"auctor.velit.eget@tempuseuligula.co.uk"),(562,"Donovan Shields",101,"nisi.sem.semper@arcuSed.org"),(563,"Illiana R. Wilson",28,"magna@insodaleselit.com"),(564,"Abdul B. Leon",93,"luctus@tempusmauriserat.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (565,"Michael F. Whitehead",89,"tempus.risus@sempercursus.co.uk"),(566,"Chadwick Pate",62,"Pellentesque.ultricies@eleifend.com"),(567,"Bryar Doyle",35,"et@justosit.net"),(568,"Herrod J. Holland",86,"nunc@velsapien.co.uk"),(569,"Keaton Rollins",95,"ipsum.nunc.id@mollisnon.com"),(570,"Gray I. Wright",34,"amet.diam@arcuCurabiturut.com"),(571,"Hoyt Joseph",27,"turpis.nec.mauris@Suspendissetristique.org"),(572,"Gage Estrada",59,"quam.elementum.at@mollis.com"),(573,"Kiara Glenn",74,"Maecenas@commodo.edu"),(574,"Tiger R. Harrison",68,"commodo.ipsum.Suspendisse@ipsumSuspendissesagittis.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (575,"Frances C. Cooley",44,"inceptos.hymenaeos.Mauris@Class.net"),(576,"Pascale A. Leach",60,"et@a.net"),(577,"Beverly A. Church",24,"augue.porttitor@etultricesposuere.edu"),(578,"Keaton V. Holcomb",80,"Sed.auctor@augueeu.edu"),(579,"Diana Underwood",30,"dis.parturient.montes@massa.net"),(580,"Wendy M. Butler",72,"nec@lacusEtiambibendum.com"),(581,"Ulla Emerson",35,"et@idenim.net"),(582,"Eagan Brewer",37,"pharetra.Nam@faucibuslectus.com"),(583,"Colton Salazar",73,"scelerisque.mollis.Phasellus@aceleifend.edu"),(584,"Noelani Z. Leonard",69,"rhoncus@SedmolestieSed.edu");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (585,"Hop Frederick",97,"Nam.tempor.diam@Integer.ca"),(586,"Melinda Wells",23,"pede@nunc.net"),(587,"Sopoline V. Reese",87,"Ut@Maecenas.co.uk"),(588,"Basil P. Bonner",59,"erat.vitae.risus@variusorci.com"),(589,"Minerva M. Flynn",81,"ut@ultricesmaurisipsum.co.uk"),(590,"Athena K. Olson",103,"mauris.rhoncus@tempor.edu"),(591,"Brenden Miles",110,"amet@tellusAenean.com"),(592,"Trevor Gay",60,"ut.dolor.dapibus@temporestac.com"),(593,"Harrison Reyes",31,"sodales.nisi@Maurisquisturpis.com"),(594,"Zena Z. Parker",71,"magna.Nam.ligula@eleifendvitae.co.uk");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (595,"Jocelyn Q. Murphy",55,"Vivamus.nibh@actellusSuspendisse.edu"),(596,"Fatima Schneider",104,"Curabitur.vel.lectus@magnaa.org"),(597,"Indira X. Boone",104,"eu@urnaUt.co.uk"),(598,"Kameko Sloan",91,"convallis.erat@vitaealiquetnec.com"),(599,"Fuller Duke",99,"ullamcorper@mollislectus.com"),(600,"Kenyon C. Frost",93,"malesuada.vel@eu.org"),(601,"Patricia B. Savage",53,"volutpat.Nulla.facilisis@elit.edu"),(602,"Marah Thompson",27,"laoreet.ipsum.Curabitur@sodales.ca"),(603,"Risa Robertson",29,"Mauris@velmaurisInteger.edu"),(604,"Vielka W. Benjamin",37,"justo@pede.com");
INSERT INTO `clientes` (`codigo_cliente`,`nome_cliente`,`idate_cliente`,`email_cliente`) VALUES (605,"Beck Mooney",36,"odio.Aliquam@a.org"),(606,"Martena Y. Lyons",45,"a.neque.Nullam@ullamcorper.co.uk"),(607,"Finn Brooks",93,"Phasellus.nulla@egestas.org"),(608,"Yoko Mcintyre",22,"ullamcorper.Duis.cursus@aliquamerosturpis.co.uk"),(609,"Aileen Mccarthy",87,"elit.dictum.eu@bibendumullamcorperDuis.co.uk"),(610,"Demetrius Brennan",55,"diam.luctus@ante.net"),(611,"Wesley Mccall",54,"Vestibulum.ante.ipsum@loremeu.co.uk"),(612,"Brady Love",76,"molestie.sodales@estNunclaoreet.net"),(613,"Quail Forbes",72,"ac.mattis.velit@ut.co.uk"),(614,"Mark Q. Clemons",55,"eget@ligulaAeneaneuismod.edu");

*/

